Edwards25519 basic arithmetic mod 2^255-19
hashcloak/fuel-crypto pull request #5
Opened 2022-10-12 18:08 UTC by ewynx

This branch contains basic arithmetic for GF(2^255 - 19). We store elements in radix-51 representation. 
We've used 2 reference implementations:
- NaCl impl (current reference from authors)
https://cr.yp.to/ecdh.html#use
- Go impl (uses same radix-51 rep)
https://cs.opensource.google/go/go/+/master:src/crypto/internal/edwards25519/field/fe.go

The functions in the `field_element` file are all tested, except for `inverse` which is too heavy and gives the Immediate18TooLarge error. 
Also functionality from `ge25519` gives that same error.

2022-10-13 11:02 UTC, Mikerah requested changes

2022-10-13 11:02 UTC, Mikerah commented on testing/tests_bls12_381/tests/utils/mod.rs
> +use fuels::{
Should be cherrypicked into its own branched or removed

2022-10-13 11:03 UTC, Mikerah commented
For the most part everything looks good

2022-10-15 22:52 UTC, ewynx commented
Cherrypicked the edwards stuff and merged [here](https://github.com/hashcloak/fuel-crypto/pull/6). Separate [commit](https://github.com/hashcloak/fuel-crypto/commit/2232627e3dfd9bd0d05382ab9b435e056993f06a) for the final small fixes. 

Everything that was in this PR is now merged and the tests of bls and edwards run as they did in the PRs.

2022-10-15 23:16 UTC, Mikerah commented
Then this PR should be closed

2022-10-15 23:16 UTC, closed without merging